create temporary table product_seed_mapping (
    family_name varchar(255) not null,
    category_name varchar(255) not null,
    store_name varchar(255) not null,
    match_value varchar(512) not null,
    variant_name varchar(255),
    variant_total_quantity numeric(12, 3),
    variant_total_unit varchar(32),
    variant_package_quantity integer,
    variant_package_description varchar(255)
) on commit drop;

insert into product_seed_mapping (
    family_name, category_name, store_name, match_value,
    variant_name, variant_total_quantity, variant_total_unit, variant_package_quantity, variant_package_description
) values
    ('Coca-Cola Zero', 'Getraenke', 'REWE', 'COCA COLA ZERO', null, null, null, null, null),
    ('Coca-Cola Zero', 'Getraenke', 'REWE', 'COCA-COLA ZERO', null, null, null, null, null),
    ('Coca-Cola Zero', 'Getraenke', 'REWE', 'CC Z 0,33L EW FL', '0.33 l Einwegflasche', 0.330, 'l', 1, 'Einwegflasche'),
    ('Sprite Zero', 'Getraenke', 'REWE', 'CC SPRITE ZERO', null, null, null, null, null),
    ('Kinder Riegel', 'Suesswaren und Snacks', 'REWE', 'KINDER RIEGEL', null, null, null, null, null),
    ('Kinder Riegel', 'Suesswaren und Snacks', 'ALDI', '317237 Kinder Riegel 10x', '10 Riegel', null, null, 10, 'Riegel'),
    ('Kinder Riegel', 'Suesswaren und Snacks', 'EDEKA', 'Kinder Riegel', null, null, null, null, null),
    ('Nutella', 'Vorrat und Fertiggerichte', 'REWE', 'NUTELLA', null, null, null, null, null),
    ('Nutella', 'Vorrat und Fertiggerichte', 'REWE', 'NUTELLA 450G+50G', '500 g', 500, 'g', 1, 'Glas'),
    ('Nutella', 'Vorrat und Fertiggerichte', 'EDEKA', 'Nutella', null, null, null, null, null),
    ('Ja! H-Milch 1,5 %', 'Milchprodukte und Eier', 'REWE', 'JA! H-MILCH 1,5%', null, null, null, null, null),
    ('H-Milch 1,5 %', 'Milchprodukte und Eier', 'ALDI', '329344 H-Milch 1.5% 1l', '1 l', 1, 'l', 1, 'Packung'),
    ('Streichgut ungesalzen', 'Milchprodukte und Eier', 'REWE', 'STREICHGUT UNGES', null, null, null, null, null),
    ('H-Schlagsahne', 'Milchprodukte und Eier', 'REWE', 'H-SCHLAGSAHNE', null, null, null, null, null),
    ('Ja! Schlagsahne', 'Milchprodukte und Eier', 'REWE', 'JA! SCHLAGSAHNE', null, null, null, null, null),
    ('Milchschnitte', 'Milchprodukte und Eier', 'REWE', 'MILCHSCHNITTE', null, null, null, null, null),
    ('Bresso Kraeuter', 'Milchprodukte und Eier', 'REWE', 'BRESSO KRAEUT', null, null, null, null, null),
    ('Eier M Bodenhaltung', 'Milchprodukte und Eier', 'REWE', 'EIER M BODENHALT', null, null, null, null, null),
    ('Eier L Bodenhaltung', 'Milchprodukte und Eier', 'REWE', 'EIER L 10ER BODE', '10 Stueck', null, null, 10, 'Eier'),
    ('Vriesen Eier Bodenhaltung', 'Milchprodukte und Eier', 'EDEKA', 'Vriesen Eier BDH', null, null, null, null, null),
    ('Gouda gerieben', 'Milchprodukte und Eier', 'REWE', 'GOUDA GER. 48%', null, null, null, null, null),
    ('Mozzarella di Bufala', 'Milchprodukte und Eier', 'REWE', 'MOZZAR.DI BUFALA', null, null, null, null, null),
    ('Mozzarella Mini leicht', 'Milchprodukte und Eier', 'REWE', 'MOZZ.MINI LEICHT', null, null, null, null, null),
    ('Mozzarella gerieben', 'Milchprodukte und Eier', 'REWE', 'MOZZARELLA GER', null, null, null, null, null),
    ('Parmigiano Reggiano', 'Milchprodukte und Eier', 'EDEKA', 'Herz.Parmigiano', null, null, null, null, null),
    ('Frischkaese natur', 'Milchprodukte und Eier', 'REWE', 'FRISCHKAESE NATU', null, null, null, null, null),
    ('Schmand 24 %', 'Milchprodukte und Eier', 'REWE', 'SCHMAND 24%', null, null, null, null, null),
    ('Speisequark mager', 'Milchprodukte und Eier', 'REWE', 'SPEISEQUARK MAG.', null, null, null, null, null),
    ('Joghurt griechische Art', 'Milchprodukte und Eier', 'REWE', 'JOGH GRIECH. ART', null, null, null, null, null),
    ('Schlemmerjoghurt', 'Milchprodukte und Eier', 'REWE', 'SCHLEMMERJOGHURT', null, null, null, null, null),
    ('Zott Monte Maxi', 'Milchprodukte und Eier', 'REWE', 'ZOTT MONTE MAXI', null, null, null, null, null),
    ('Actimel Erdbeer', 'Milchprodukte und Eier', 'REWE', 'ACTIMEL ERDBEER', null, null, null, null, null),
    ('Muellermilch', 'Milchprodukte und Eier', 'REWE', 'MUELLERMILCH', null, null, null, null, null),
    ('Sahnepudding', 'Milchprodukte und Eier', 'REWE', 'SAHNEPUDDING', null, null, null, null, null),
    ('Griesspudding', 'Milchprodukte und Eier', 'REWE', 'GRIESSPUDDING', null, null, null, null, null),
    ('Kakao-Mousse', 'Milchprodukte und Eier', 'REWE', 'KAKAO-MOUSSE', null, null, null, null, null),
    ('Karotten', 'Salat, Obst & Gemüse', 'REWE', 'KAROTTE', null, null, null, null, null),
    ('Karotten', 'Salat, Obst & Gemüse', 'REWE', 'KAROTTE M. GRUEN', null, null, null, null, null),
    ('Karotten', 'Salat, Obst & Gemüse', 'REWE', 'KAROTTE REWE PP', null, null, null, null, null),
    ('Bio Karotten', 'Salat, Obst & Gemüse', 'ALDI', '495578 Karotten Bio 1kg', '1 kg', 1, 'kg', 1, 'Beutel'),
    ('Speisezwiebeln', 'Salat, Obst & Gemüse', 'REWE', 'SPEISEZWIEBELN', null, null, null, null, null),
    ('Lauchzwiebeln', 'Salat, Obst & Gemüse', 'REWE', 'LAUCHZWIEBELN', null, null, null, null, null),
    ('Schalotten', 'Salat, Obst & Gemüse', 'REWE', 'SCHALOTTEN REGIO', null, null, null, null, null),
    ('Cherry-Rispentomaten', 'Salat, Obst & Gemüse', 'REWE', 'TOMATE CHERRYROM', null, null, null, null, null),
    ('Cherry-Rispentomaten', 'Salat, Obst & Gemüse', 'REWE', 'CHERRYROMATOMATE', null, null, null, null, null),
    ('Rispentomaten', 'Salat, Obst & Gemüse', 'REWE', 'TOMATE RISPE RL', null, null, null, null, null),
    ('Bananen', 'Salat, Obst & Gemüse', 'REWE', 'BANANE', null, null, null, null, null),
    ('Bananen', 'Salat, Obst & Gemüse', 'REWE', 'BANANE BANDEROLE', null, null, null, null, null),
    ('Chiquita Bananen', 'Salat, Obst & Gemüse', 'REWE', 'BANANE CHIQUITA', null, null, null, null, null),
    ('Champignons weiss', 'Salat, Obst & Gemüse', 'REWE', 'CHAMPIGNON WEISS', null, null, null, null, null),
    ('Champignons', 'Salat, Obst & Gemüse', 'REWE', 'CHAMPIGNONS', null, null, null, null, null),
    ('Zucchini gruen', 'Salat, Obst & Gemüse', 'REWE', 'ZUCCHINI GRUEN', null, null, null, null, null),
    ('Paprika rot', 'Salat, Obst & Gemüse', 'REWE', 'PAPRIKA ROT', null, null, null, null, null),
    ('Eisbergsalat', 'Salat, Obst & Gemüse', 'REWE', 'EISBERGSALAT', null, null, null, null, null),
    ('Roma-Herzsalat', 'Salat, Obst & Gemüse', 'REWE', 'SALAT ROMA HERZ', null, null, null, null, null),
    ('Gurkensalat', 'Salat, Obst & Gemüse', 'REWE', 'GURKENSALAT', null, null, null, null, null),
    ('Weisskrautsalat', 'Salat, Obst & Gemüse', 'REWE', 'WEISSKRAUTSAL.DI', null, null, null, null, null),
    ('Cole Slaw Salat', 'Salat, Obst & Gemüse', 'REWE', 'COLE SLAW SALAT', null, null, null, null, null),
    ('Erbsen und Moehrchen', 'Salat, Obst & Gemüse', 'REWE', 'ERBSEN MOEHRCHEN', null, null, null, null, null),
    ('Zuckermais', 'Salat, Obst & Gemüse', 'REWE', 'ZUCKERMAIS', null, null, null, null, null),
    ('Goldmais', 'Salat, Obst & Gemüse', 'REWE', 'GOLDMAIS', null, null, null, null, null),
    ('Bonduelle Texas Mix', 'Salat, Obst & Gemüse', 'REWE', 'TEXAS MIX', null, null, null, null, null),
    ('Bonduelle Country Mix', 'Salat, Obst & Gemüse', 'REWE', 'COUNTRY MIX', null, null, null, null, null),
    ('Schinkenfleischwurst', 'Fleisch und Wurst', 'REWE', 'SCHINKENFLEISCHW', null, null, null, null, null),
    ('Kesselschinken', 'Fleisch und Wurst', 'REWE', 'KESSELSCHINKEN', null, null, null, null, null),
    ('Schweinebraten', 'Fleisch und Wurst', 'REWE', 'SCHWEINEBRATEN', null, null, null, null, null),
    ('Leberwurst grob', 'Fleisch und Wurst', 'REWE', 'LEBERW.GROB GDD', null, null, null, null, null),
    ('Knoblauchsalami', 'Fleisch und Wurst', 'REWE', 'KNOB.SALAMI ZEHE', null, null, null, null, null),
    ('Kasslerbraten', 'Fleisch und Wurst', 'REWE', 'KASSLERBRATEN', null, null, null, null, null),
    ('Knoblauchwurst', 'Fleisch und Wurst', 'REWE', 'KNOBLAUCHWURST', null, null, null, null, null),
    ('Fleischwurst', 'Fleisch und Wurst', 'REWE', 'FLEISCHWURST', null, null, null, null, null),
    ('Bratwurst grob', 'Fleisch und Wurst', 'REWE', 'BRATWURST GROB', null, null, null, null, null),
    ('Hackfleisch', 'Fleisch und Wurst', 'REWE', 'HACKFLEISCH', null, null, null, null, null),
    ('Hackfleisch gemischt', 'Fleisch und Wurst', 'REWE', 'HACKFLEISCH GEM', null, null, null, null, null),
    ('Schweinefilet', 'Fleisch und Wurst', 'REWE', 'SCHWEINEFILET', null, null, null, null, null),
    ('Schweinemett', 'Fleisch und Wurst', 'REWE', 'SCHWEINEMETT', null, null, null, null, null),
    ('Hähnchenbrustfilet', 'Fleisch und Wurst', 'REWE', 'HA-BRUSTFILET', null, null, null, null, null),
    ('Hähnchenbrust', 'Fleisch und Wurst', 'REWE', 'HAEHN.BRUST', null, null, null, null, null),
    ('Hähnchenfleisch in Aspik', 'Fleisch und Wurst', 'REWE', 'HAEHNCH.FL.ASPIK', null, null, null, null, null),
    ('Paprikalyoner', 'Fleisch und Wurst', 'REWE', 'PAPRIKALYONER', null, null, null, null, null),
    ('Italienische Mortadella', 'Fleisch und Wurst', 'REWE', 'ITAL.MORTAD.CAST', null, null, null, null, null),
    ('Pommern Leberwurst fein', 'Fleisch und Wurst', 'REWE', 'POMM.LEBERW.FEIN', null, null, null, null, null),
    ('Salinenschinken', 'Fleisch und Wurst', 'REWE', 'SALINENSCHINKEN', null, null, null, null, null),
    ('Vespermett', 'Fleisch und Wurst', 'REWE', 'VESPERMETT .', null, null, null, null, null),
    ('Rohschinken', 'Fleisch und Wurst', 'REWE', 'ROHSCHINKEN GEW.', null, null, null, null, null),
    ('Wacholderschinken', 'Fleisch und Wurst', 'REWE', 'WACHOLDERSCHINK.', null, null, null, null, null),
    ('Wiener Wuerstchen', 'Fleisch und Wurst', 'REWE', 'WIENER WUERST.', null, null, null, null, null),
    ('Haribo Super Gurken', 'Suesswaren und Snacks', 'REWE', 'SUPER GURKEN', null, null, null, null, null),
    ('Haribo Tropifrutti', 'Suesswaren und Snacks', 'REWE', 'HARIBO TROPI FRU', null, null, null, null, null),
    ('Haribo Goldbaeren', 'Suesswaren und Snacks', 'REWE', 'HARIBO GOLDBAER', null, null, null, null, null),
    ('Haribo Goldbaeren Minis', 'Suesswaren und Snacks', 'REWE', 'GOLDBAEREN MINIS', null, null, null, null, null),
    ('Haribo Pfirsiche', 'Suesswaren und Snacks', 'REWE', 'HARIBO PFIRSICHE', null, null, null, null, null),
    ('Chipsfrisch', 'Suesswaren und Snacks', 'REWE', 'CHIPSFRISCH', null, null, null, null, null),
    ('Chipsfrisch ungarisch', 'Suesswaren und Snacks', 'REWE', 'CHIPSF.UNGA.', null, null, null, null, null),
    ('Smarties', 'Suesswaren und Snacks', 'REWE', 'SMARTIES VM', null, null, null, null, null),
    ('Smarties Riesenrolle', 'Suesswaren und Snacks', 'EDEKA', 'Smarties Ries.Rol.', null, null, null, null, null),
    ('Milky Way', 'Suesswaren und Snacks', 'REWE', 'MILKY WAY 9ER', '9 Riegel', null, null, 9, 'Riegel'),
    ('Milky Way Minis', 'Suesswaren und Snacks', 'Jawoll', 'Milky Way Minis', null, null, null, null, null),
    ('Bounty Minis', 'Suesswaren und Snacks', 'Jawoll', 'Bounty Minis', null, null, null, null, null),
    ('Super Dickmanns', 'Suesswaren und Snacks', 'Jawoll', 'Super Dickmanns 9er', '9 Stueck', null, null, 9, 'Stueck'),
    ('Funny-Frisch ungarisch', 'Suesswaren und Snacks', 'ALDI', '754753 FF Ungarisch 175g', '175 g', 175, 'g', 1, 'Beutel'),
    ('Funny-Frisch Chipsfrisch', 'Suesswaren und Snacks', 'ALDI', '461487 FF Chipsfr. 150g', '150 g', 150, 'g', 1, 'Beutel'),
    ('Choceur Sahne und Weisse', 'Suesswaren und Snacks', 'ALDI', '297776 Chocr Sahne&amp;Weiße', null, null, null, null, null),
    ('Schokostreusel', 'Suesswaren und Snacks', 'ALDI', '187199 Schokostreusel', null, null, null, null, null),
    ('Nesquik Original', 'Vorrat und Fertiggerichte', 'EDEKA', 'Nesquik Original', null, null, null, null, null),
    ('Thomy Remoulade', 'Vorrat und Fertiggerichte', 'EDEKA', 'Thomy Remoulade', null, null, null, null, null),
    ('Remoulade', 'Vorrat und Fertiggerichte', 'REWE', 'REMOULADE', null, null, null, null, null),
    ('Basmati Reis', 'Vorrat und Fertiggerichte', 'REWE', 'BASMATI KB', null, null, null, null, null),
    ('Sauce Hollandaise', 'Vorrat und Fertiggerichte', 'REWE', 'SAUCEHOLLANDAISE', null, null, null, null, null),
    ('Sauce Hollandaise leicht', 'Vorrat und Fertiggerichte', 'REWE', 'HOLLANDAISE LEG.', null, null, null, null, null),
    ('Pesto Rosso', 'Vorrat und Fertiggerichte', 'REWE', 'PESTO ROSSO', null, null, null, null, null),
    ('Pesto Ricotta', 'Vorrat und Fertiggerichte', 'REWE', 'PESTO RICOTTA', null, null, null, null, null),
    ('Ja! Paniermehl', 'Vorrat und Fertiggerichte', 'REWE', 'JA! PANIERMEHL', null, null, null, null, null),
    ('Weizensandwich Vollkorn', 'Brot und Backwaren', 'REWE', 'WEIZENVOLLK.SAND', null, null, null, null, null),
    ('Toast', 'Brot und Backwaren', 'REWE', 'TOAST SKS', null, null, null, null, null),
    ('Baguette Bolognese', 'Brot und Backwaren', 'REWE', 'BAGUETTE BOLOGN.', null, null, null, null, null),
    ('Abteibrot', 'Brot und Backwaren', 'ALDI', '267722 Abteibrot', null, null, null, null, null),
    ('Buesch Brot', 'Brot und Backwaren', 'Büsch GmbH', 'Büsch auf 30Die.', null, null, null, null, null),
    ('Stille Quelle', 'Getraenke', 'REWE', 'STILLE QUELLE', null, null, null, null, null),
    ('Orange Saft', 'Getraenke', 'REWE', 'ORANGE SAFT', null, null, null, null, null),
    ('Red Bull Dose', 'Getraenke', 'REWE', 'RED BULL DOSE', null, null, null, null, null),
    ('Rotbaeckchen Klassik', 'Getraenke', 'REWE', 'ROTB. KLASSIK', null, null, null, null, null),
    ('Rotbaeckchen Original', 'Getraenke', 'dm', 'Rotbäckchen Original 1', null, null, null, null, null),
    ('Rotbaeckchen Immunstark', 'Getraenke', 'dm', 'Rotbäckchen Immunstark', null, null, null, null, null),
    ('Denkmit Destilliertes Wasser', 'Haushalt', 'dm', 'Denkmit Destilliert. Wasser 5L', '5 l', 5, 'l', 1, 'Kanister'),
    ('Denkmit Destilliertes Wasser', 'Haushalt', 'dm', 'Denkmit Destilliert. Wasser 2L', '2 l', 2, 'l', 1, 'Flasche'),
    ('Denkmit Destilliertes Wasser', 'Haushalt', 'dm', 'Denkmit Destilliert.', null, null, null, null, null),
    ('Denkmit Duft-Gel Ocean', 'Haushalt', 'dm', 'Denkmit Duft-Gel Ocean', null, null, null, null, null),
    ('Kleenex Taschentuecher', 'Haushalt', 'dm', 'Kleenex Taschentücher', null, null, null, null, null),
    ('Kleenex Taschentuecher Disney', 'Haushalt', 'dm', 'Kleenex Taschentücher Disney', null, null, null, null, null),
    ('Soft und Sicher Taschentuecher', 'Haushalt', 'dm', 'Soft&Sicher TatüboxDes', null, null, null, null, null),
    ('Soft und Sicher Taschentuecher', 'Haushalt', 'dm', 'Soft&Sicher Taschent. 42x10St', null, null, null, null, null),
    ('Profissimo Einkaufstasche', 'Haushalt', 'dm', 'Profissimo Einkaufstasche uni', null, null, null, null, null),
    ('Profissimo Topfschwaemme', 'Haushalt', 'dm', 'Prof. Trio-Topfschwämme 2St', '2 Stueck', null, null, 2, 'Schwaemme'),
    ('Profissimo Gefrierbeutel', 'Haushalt', 'dm', 'Prof. 3L Gefrierb. Sch', null, null, null, null, null),
    ('Profissimo Faltbarer Eimer', 'Haushalt', 'dm', 'Profissimo Faltbarer Eimer', null, null, null, null, null),
    ('Frosch Baby Spuel-Reiniger', 'Haushalt', 'dm', 'Frosch Baby Spül-Reiniger', null, null, null, null, null),
    ('Frosch Vollwaschmittel Baby', 'Haushalt', 'dm', 'Frosch Vollwaschmittel Baby', null, null, null, null, null),
    ('Frosch Waesche-Weich Baby', 'Haushalt', 'dm', 'Frosch WSP Baby Wäsche-Weich', null, null, null, null, null),
    ('Mivolis Meerwasser Nasenspray', 'Gesundheit', 'dm', 'Mivolis Meerwasser Nas', null, null, null, null, null),
    ('Mivolis Inhalationsloesung', 'Gesundheit', 'dm', 'Mivolis Inhalationslösung 75ml', '75 ml', 75, 'ml', 1, 'Flasche'),
    ('Mivolis Magnesium 300', 'Gesundheit', 'dm', 'Mivolis Magnesium 300 St', null, null, null, null, null),
    ('Mivolis Omega-3 1000', 'Gesundheit', 'dm', 'Mivolis Omega-3 1000 Kapseln', null, null, null, null, null),
    ('TENA Discreet Ultra', 'Gesundheit', 'dm', 'TENA Discreet Ultra BS 16St', '16 Stueck', null, null, 16, 'Einlagen'),
    ('TENA lights', 'Gesundheit', 'dm', 'TENA lights SlipEinlagen Light', null, null, null, null, null),
    ('o.b. Original Super Plus', 'Gesundheit', 'dm', 'o.b. Original Super Plus 32er', '32 Stueck', null, null, 32, 'Tampons'),
    ('Balea Schaumbad Milch', 'Koerperpflege', 'dm', 'Balea Schaumbad Milch', null, null, null, null, null),
    ('Buebchen Traum-Bad und Dusche', 'Koerperpflege', 'dm', 'Bübchen Traum-Bad&Dusche 500ml', '500 ml', 500, 'ml', 1, 'Flasche'),
    ('Gliss Express-Repair-Spuelung', 'Koerperpflege', 'dm', 'Gliss Expr.-Rep.Spülung to.Rep', null, null, null, null, null),
    ('Labello Original', 'Koerperpflege', 'dm', 'Labello Lippenpfl. Original DP', null, null, null, null, null),
    ('La Rive Extreme Story Eau de Toilette', 'Koerperpflege', 'dm', 'La Rive Extreme Story EdT75ml', '75 ml', 75, 'ml', 1, 'Flakon'),
    ('Babylove Wickelunterlage', 'Baby und Kind', 'dm', 'babylove Wickelunterla', null, null, null, null, null),
    ('Babylove Betteinlagen', 'Baby und Kind', 'dm', 'babylove Betteinlagen', null, null, null, null, null),
    ('Babylove Stilleinlagen', 'Baby und Kind', 'dm', 'babylove mama Stilleinlagen we', null, null, null, null, null),
    ('Babylove Stilleinlagen', 'Baby und Kind', 'dm', 'babylove mama Stilleinlage ex.', null, null, null, null, null),
    ('Babylove Beissring', 'Baby und Kind', 'dm', 'babylove Beißring 1St', '1 Stueck', null, null, 1, 'Beissring'),
    ('Babylove Nasensauger', 'Baby und Kind', 'dm', 'babylove Nasensauger 1St', '1 Stueck', null, null, 1, 'Nasensauger'),
    ('Babylove Flaschenbuerste', 'Baby und Kind', 'dm', 'babylove Prem. Fl.buerste 1St', '1 Stueck', null, null, 1, 'Buerste'),
    ('Babylove Schwimmwindel', 'Baby und Kind', 'dm', 'babylove Schwimmwindel Gr.', null, null, null, null, null),
    ('Babylove Sonnensegel', 'Baby und Kind', 'dm', 'babylove Sonnensegel', null, null, null, null, null),
    ('Babylove Stoffrassel', 'Baby und Kind', 'dm', 'babylove Stoffrassel 1St', '1 Stueck', null, null, 1, 'Stoffrassel'),
    ('Babylove Windelbeutel', 'Baby und Kind', 'dm', 'babylove Windelbeutel 100St', '100 Stueck', null, null, 100, 'Beutel'),
    ('Aptamil Care Pre Anfangsmilch', 'Baby und Kind', 'dm', 'Aptamil CarePre Anf.milch 800g', '800 g', 800, 'g', 1, 'Dose'),
    ('HiPP Baby Pflegebad', 'Baby und Kind', 'dm', 'HiPP Baby Pflegebad 200ml', '200 ml', 200, 'ml', 1, 'Flasche'),
    ('HiPP Babysanft Milk Lotion', 'Baby und Kind', 'dm', 'HiPP Babysanft MilkLotion350ml', '350 ml', 350, 'ml', 1, 'Flasche'),
    ('HiPP Babysanft Pflegecreme', 'Baby und Kind', 'dm', 'HiPP Babysanft Pflegecreme75ml', '75 ml', 75, 'ml', 1, 'Tube'),
    ('HiPP Babysanft Shampoo', 'Baby und Kind', 'dm', 'HiPP Babysanft Shampoo 200ml', '200 ml', 200, 'ml', 1, 'Flasche'),
    ('HiPP Babysanft Waschgel', 'Baby und Kind', 'dm', 'HiPP Babysanft Waschgel 400ml', '400 ml', 400, 'ml', 1, 'Flasche'),
    ('HiPP Babysanft Tücher', 'Baby und Kind', 'dm', 'Hipp Babysanft Tücher 20St', '20 Stueck', null, null, 20, 'Tücher'),
    ('HiPP Bio-Karotte', 'Baby und Kind', 'dm', 'Hipp Reine Bio-Karotte', null, null, null, null, null),
    ('Weleda Calendula Pflegecreme', 'Baby und Kind', 'dm', 'Weleda Calendula Pflegecreme', null, null, null, null, null),
    ('Weleda Calendula Waschlotion und Shampoo', 'Baby und Kind', 'dm', 'Weleda Calendula Waschl.&Shamp', null, null, null, null, null),
    ('dm Fotoauftrag', 'Fotos & Bilder', 'dm', 'Fotoauftrag', null, null, null, null, null),
    ('dm Fotoexpress', 'Fotos & Bilder', 'dm', 'Fotoexpress', null, null, null, null, null),
    ('McDonalds Cheeseburger', 'Gastronomie', 'McDonald''s', 'Cheeseburger', null, null, null, null, null),
    ('McDonalds Hamburger Royal TS', 'Gastronomie', 'McDonald''s', 'Hamburger Royal TS', null, null, null, null, null),
    ('McDonalds Filet-o-Fish', 'Gastronomie', 'McDonald''s', '2x Filet-o-Fish®', null, null, null, null, null),
    ('McDonalds Big Mac', 'Gastronomie', 'McDonald''s', '2 Klassiker nach Wahl Big Mac®', null, null, null, null, null),
    ('Fluconazol Accord 50 mg', 'Gesundheit', 'alex apotheke', 'FLUCONAZOL ACCORD 50MG 1 HKP 14 ST', '14 Stueck', null, null, 14, 'Kapseln'),
    ('WICK Nasivin Dostr Baby', 'Gesundheit', 'alex apotheke', 'WICK NASIVIN DOSTR OK BABY (N1)', null, null, null, null, null),
    ('Advantan Creme', 'Gesundheit', 'apotheke am lessingplatz', 'ADVANTAN CREME CRE 25g', '25 g', 25, 'g', 1, 'Tube'),
    ('Bexsero Injektionssuspension', 'Gesundheit', 'apotheke am lessingplatz', 'BEXSEROINJEKTIONSSUSP FER ISU 1X0.5ml', '0.5 ml', 0.5, 'ml', 1, 'Dosis'),
    ('Hexyon Injektionssuspension', 'Gesundheit', 'apotheke am lessingplatz', 'HEXYON INJ.-SUSP.O.KANUELE ISU 0.5ml', '0.5 ml', 0.5, 'ml', 1, 'Dosis'),
    ('Vaxneuvance Injektion', 'Gesundheit', 'apotheke am lessingplatz', 'VAXNEUVANCE ISU I E FER ISU 1St', '1 Stueck', null, null, 1, 'Dosis'),
    ('Diesel', 'Mobilitaet und Tanken', 'star Tankstelle', 'Diesel', null, null, null, null, null),
    ('Einstreu', 'Tierbedarf', 'LANDMARKT OFFER', 'Einstreu T2', null, null, null, null, null),
    ('Einstreu', 'Tierbedarf', 'LANDMARKT OFFER', 'Einstreu 12', null, null, null, null, null),
    ('C&A Baby Kombi', 'Baby und Kind', 'C&A', 'BABY-COMBI Größe 074', 'Groesse 074', null, null, 1, 'Kleidungsstueck'),
    ('C&A Baby Tops', 'Baby und Kind', 'C&A', 'BABY-TOPS Größe 074', 'Groesse 074', null, null, 1, 'Kleidungsstueck'),
    ('C&A Baby Hose', 'Baby und Kind', 'C&A', 'BABY-HOSE Farbe 1 Große 068', 'Groesse 068', null, null, 1, 'Kleidungsstueck'),
    ('C&A Baby Hose', 'Baby und Kind', 'C&A', 'BABY-HOSE Farbe 1 Große 074', 'Groesse 074', null, null, 1, 'Kleidungsstueck'),
    ('C&A Baby Outdoor', 'Baby und Kind', 'C&A', 'B-OUTDOOR Größe 074', 'Groesse 074', null, null, 1, 'Kleidungsstueck'),
    ('C&A Baby Waesche', 'Baby und Kind', 'C&A', 'B-WAESCHE Größe 074', 'Groesse 074', null, null, 1, 'Kleidungsstueck'),
    ('DaHerr Bio Pantolette', 'Kleidung und Schuhe', 'Jawoll', 'Da/He Bio Pantolette', null, null, null, null, null),
    ('Chlortabs Super', 'Baumarkt und Garten', 'Jawoll', 'Chlortaß-Super 1kg', '1 kg', 1, 'kg', 1, 'Eimer'),
    ('Edelgeranie', 'Baumarkt und Garten', 'Jawoll', 'Edelgeranie 23cm', '23 cm', 23, 'cm', 1, 'Topf'),
    ('Schleierkraut', 'Baumarkt und Garten', 'Jawoll', 'Schleierkraut 23cm', '23 cm', 23, 'cm', 1, 'Topf'),
    ('Wellenbox', 'Haushalt', 'Jawoll', 'Wellenbox 17L', '17 l', 17, 'l', 1, 'Box'),
    ('Trinkbecher', 'Haushalt', 'Jawoll', '100 Trinkbecher 0,2l', '0.2 l', 0.2, 'l', 100, 'Trinkbecher');

insert into product_family (name, default_category_id)
select distinct mapping.family_name, category.id
from product_seed_mapping mapping
join category on category.name = mapping.category_name
on conflict (name) do nothing;

insert into product_variant (
    product_family_id,
    name,
    package_quantity,
    package_description,
    total_quantity,
    total_unit
)
select distinct
    family.id,
    mapping.variant_name,
    mapping.variant_package_quantity,
    mapping.variant_package_description,
    mapping.variant_total_quantity,
    mapping.variant_total_unit
from product_seed_mapping mapping
join product_family family on family.name = mapping.family_name
where mapping.variant_name is not null
on conflict (product_family_id, name) do nothing;

insert into product_rule (
    product_family_id,
    product_variant_id,
    store_name,
    match_type,
    match_value,
    priority
)
select distinct
    family.id,
    variant.id,
    mapping.store_name,
    'EXACT',
    mapping.match_value,
    100
from product_seed_mapping mapping
join product_family family on family.name = mapping.family_name
left join product_variant variant
    on variant.product_family_id = family.id
    and variant.name = mapping.variant_name
where not exists (
    select 1
    from product_rule existing
    where existing.product_family_id = family.id
      and existing.product_variant_id is not distinct from variant.id
      and existing.store_name is not distinct from mapping.store_name
      and existing.match_type = 'EXACT'
      and existing.match_value = mapping.match_value
);
