create temporary table additional_product_seed_mapping (
    family_name varchar(255) not null,
    category_name varchar(255) not null,
    store_name varchar(255) not null,
    match_value varchar(512) not null
) on commit drop;

insert into additional_product_seed_mapping (family_name, category_name, store_name, match_value) values
    ('Toilettenpapier 3-lagig', 'Haushalt', 'REWE', 'TOILETTENPAP.3LG'),
    ('Kuechentuecher', 'Haushalt', 'REWE', 'KUECHENTUECHER'),
    ('Kraeuterbutter', 'Milchprodukte und Eier', 'REWE', 'KRAEUTERBUTTER'),
    ('Kartoffeln dick', 'Salat, Obst & Gemüse', 'REWE', 'KARTOFFELN DICK'),
    ('Kartoffeln', 'Salat, Obst & Gemüse', 'REWE', 'KARTOFFELN'),
    ('Apfel Elstar', 'Salat, Obst & Gemüse', 'REWE', 'APFEL ELSTAR'),
    ('Kiwi Gold', 'Salat, Obst & Gemüse', 'REWE', 'KIWI GOLD'),
    ('Kiwi', 'Salat, Obst & Gemüse', 'REWE', 'KIWI'),
    ('Blumenkohl', 'Salat, Obst & Gemüse', 'REWE', 'BLUMENKOHL WEISS'),
    ('Kohlrabi', 'Salat, Obst & Gemüse', 'REWE', 'KOHLRABI'),
    ('Porree', 'Salat, Obst & Gemüse', 'REWE', 'PORREE'),
    ('Petersilie', 'Salat, Obst & Gemüse', 'REWE', 'PETERSILIE'),
    ('Stangenspargel', 'Salat, Obst & Gemüse', 'REWE', 'STANGENSPARGEL'),
    ('Wachsbrechbohnen', 'Salat, Obst & Gemüse', 'REWE', 'WACHSBRECHBOHNEN'),
    ('Rahmspinat', 'Salat, Obst & Gemüse', 'REWE', 'RAHM SPINAT'),
    ('Kidneybohnen', 'Salat, Obst & Gemüse', 'REWE', 'KIDNEY BOHNEN'),
    ('Kirschtomaten Paprika', 'Salat, Obst & Gemüse', 'REWE', 'KIRSCHPAPRIKA'),
    ('Gefluegelsalat', 'Fleisch und Wurst', 'REWE', 'GEFLUEGELSALAT'),
    ('Grillsaftschinken', 'Fleisch und Wurst', 'REWE', 'GRILLSAFTSCHINKE'),
    ('Koelner Leberwurst', 'Fleisch und Wurst', 'REWE', 'KOELNER LEBERW.'),
    ('Pfaelzer Leberwurst', 'Fleisch und Wurst', 'REWE', 'PFAEL.LEBERWURST'),
    ('Pfaelzer Leberwurst', 'Fleisch und Wurst', 'REWE', 'PFAELZ.LEBERW.'),
    ('Backesschinken', 'Fleisch und Wurst', 'REWE', 'BACKESSCHINKEN'),
    ('Butterschinken', 'Fleisch und Wurst', 'REWE', 'BUTTERSCHINKEN'),
    ('Delikatess Kochschinken', 'Fleisch und Wurst', 'REWE', 'DEL. KOCHSCHINK.'),
    ('Bauchscheiben', 'Fleisch und Wurst', 'REWE', 'BAUCHSCHEIBEN'),
    ('Kasseler Lachs', 'Fleisch und Wurst', 'REWE', 'KASSELER LACHS'),
    ('Pfanne Gyros', 'Fleisch und Wurst', 'REWE', 'PFANNE GYROS'),
    ('Rueckensteak', 'Fleisch und Wurst', 'REWE', 'RUECKENSTEAK'),
    ('Steakhuefte', 'Fleisch und Wurst', 'REWE', 'STEAKHUEFT FR'),
    ('Zwiebel-Fleisch', 'Fleisch und Wurst', 'REWE', 'ZWIEBELFLEISCH'),
    ('Fischstaebchen', 'Fisch und Meeresfruechte', 'REWE', '15FISCHSTAEBCHEN'),
    ('Raeucherlachs', 'Fisch und Meeresfruechte', 'REWE', 'RAUECHERLACHS'),
    ('Pflanzencreme', 'Vorrat und Fertiggerichte', 'REWE', 'PFLANZENCREME'),
    ('Erdbeer-Konfituere', 'Vorrat und Fertiggerichte', 'REWE', 'ERDBEER KONFITUE'),
    ('Linsen-Eintopf', 'Vorrat und Fertiggerichte', 'REWE', 'LINSEN EINTOPF'),
    ('Weinsauerkraut', 'Vorrat und Fertiggerichte', 'REWE', 'WEINSAUERKRAUT'),
    ('Tomaten stueckig', 'Vorrat und Fertiggerichte', 'REWE', 'TOMATEN STUECKIG'),
    ('Gewuerzsauce', 'Vorrat und Fertiggerichte', 'REWE', 'WUERZSAUCE'),
    ('Vanillinzucker', 'Vorrat und Fertiggerichte', 'REWE', 'VANILLINZUCKER'),
    ('Saucenbinder', 'Vorrat und Fertiggerichte', 'REWE', 'SAUCENBINDER'),
    ('Honig', 'Vorrat und Fertiggerichte', 'REWE', 'BLUETENHONIG FL'),
    ('Instant-Mehl', 'Vorrat und Fertiggerichte', 'REWE', 'INSTANT-MEHL'),
    ('Knusperflakes', 'Vorrat und Fertiggerichte', 'REWE', 'KNUSPERFLAKES'),
    ('Frosties', 'Vorrat und Fertiggerichte', 'REWE', 'FROSTIES'),
    ('Honig-Peperoni', 'Vorrat und Fertiggerichte', 'REWE', 'HONEYPEPPERS'),
    ('Oregano gerebelt', 'Vorrat und Fertiggerichte', 'REWE', 'OREGANO GEREB.'),
    ('Oliven mit Mandeln', 'Vorrat und Fertiggerichte', 'REWE', 'OLIVEN MANDELN'),
    ('Spinat-Ricotta-Tortelloni', 'Vorrat und Fertiggerichte', 'REWE', 'SPIN. RIC. TORT.'),
    ('5 Minuten Spaghetti Tomate', 'Vorrat und Fertiggerichte', 'REWE', '5MIN SPAGH TO'),
    ('5 Minuten Spaghetti Bolognese', 'Vorrat und Fertiggerichte', 'REWE', '5MIN SPAGHBOLO'),
    ('Baked Potatoes', 'Vorrat und Fertiggerichte', 'REWE', 'BAKED POTATOES'),
    ('Antipastiteller', 'Vorrat und Fertiggerichte', 'REWE', 'ANTIPASTITELLER'),
    ('Gurke und Kartoffelsalat', 'Salat, Obst & Gemüse', 'REWE', 'DIE FEINEN KART.'),
    ('Joghurt mit Smarties', 'Milchprodukte und Eier', 'REWE', 'JOGHURT & SMART.'),
    ('Himbeerjoghurt mit Vanille', 'Milchprodukte und Eier', 'REWE', 'HIMBEER M.VANIL.'),
    ('Joghurt', 'Milchprodukte und Eier', 'REWE', 'JOGHURT'),
    ('Creme Legere', 'Milchprodukte und Eier', 'REWE', 'CREME LEGERE'),
    ('Vanille-Sosse', 'Milchprodukte und Eier', 'REWE', 'VANILLE-SOSSE'),
    ('Chester Schmelzkaese', 'Milchprodukte und Eier', 'REWE', 'CHESTER SKS'),
    ('Ja! Schmelzkaese', 'Milchprodukte und Eier', 'REWE', 'JA! SCHMELZKAESE'),
    ('Gratinkaese leicht', 'Milchprodukte und Eier', 'REWE', 'GRATINKAESE LE.'),
    ('Rote Gruetze', 'Milchprodukte und Eier', 'REWE', 'ROTE GRUETZE'),
    ('Fruchtzwerge', 'Milchprodukte und Eier', 'REWE', 'FRUCHTZWERGE'),
    ('Edelvollmilch', 'Milchprodukte und Eier', 'REWE', 'EDEL-VOLLMILCH'),
    ('Zaziki', 'Milchprodukte und Eier', 'REWE', 'ZAZIKI 8%'),
    ('Kinder Bueno', 'Suesswaren und Snacks', 'REWE', 'KINDER BUENO'),
    ('Kinder Bueno', 'Suesswaren und Snacks', 'REWE', 'KINDER BUENO 10'),
    ('Kinder Osterhase', 'Suesswaren und Snacks', 'REWE', 'KINDER OSTERHASE'),
    ('Kinderschokolade', 'Suesswaren und Snacks', 'REWE', 'KINDER SCHOKOLAD'),
    ('Kinderschokolade', 'Suesswaren und Snacks', 'REWE', 'KINDERSCHOKOLADE'),
    ('Corny Schokofree', 'Suesswaren und Snacks', 'REWE', 'CORNY SCHOKOFREE'),
    ('Corny mit Schokolade', 'Suesswaren und Snacks', 'REWE', 'CORNY W.SCHOKO'),
    ('Duplo White', 'Suesswaren und Snacks', 'REWE', 'DUPLO WHITE 10ER'),
    ('Bueno White', 'Suesswaren und Snacks', 'REWE', 'BUENO 6ER WHITE'),
    ('Hanuta', 'Suesswaren und Snacks', 'REWE', 'HANUTA 10ER'),
    ('Amicelli Tafel', 'Suesswaren und Snacks', 'REWE', 'AMICELLI TAFEL'),
    ('Choco Crossies', 'Suesswaren und Snacks', 'REWE', 'CHOCO CROSSIES'),
    ('Mousse au Chocolat', 'Suesswaren und Snacks', 'REWE', 'MOUSSE AU CHOCOL'),
    ('Sahnepudding Schokolade', 'Suesswaren und Snacks', 'REWE', 'SAHNEPU. SCHOKO'),
    ('Sahnepudding Schokolade', 'Suesswaren und Snacks', 'REWE', 'SAHNEPUD.SCHOKO'),
    ('Toffifee', 'Suesswaren und Snacks', 'REWE', 'TOFFIFEE 15ER'),
    ('Milka Pralines', 'Suesswaren und Snacks', 'REWE', 'MILKA PRALINES'),
    ('Mozartkugeln', 'Suesswaren und Snacks', 'REWE', 'MOZART KUGEL 8ER'),
    ('Erdnuesse', 'Suesswaren und Snacks', 'REWE', 'ERDNUESSE'),
    ('Marzipandecke', 'Suesswaren und Snacks', 'REWE', 'F.MARZIPAN DECKE'),
    ('Tortenglocke', 'Haushalt', 'REWE', 'TORTENGLOCKE'),
    ('Ultraspuelmittel Windfrisch', 'Haushalt', 'REWE', 'ULTRA WINDFRISCH'),
    ('Q-tips Nachfuellpack', 'Haushalt', 'REWE', 'Q-TIPS NACHFUELL'),
    ('REWE Mehrweg-Tasche', 'Haushalt', 'REWE', 'RPP TASCHE REWE'),
    ('Taschentuecher Box', 'Haushalt', 'ALDI', '446840 Taschentücher Box'),
    ('Baby Schlupfhose', 'Baby und Kind', 'ALDI', '701900 Ba Schlupfhose'),
    ('Gewuerzquark', 'Milchprodukte und Eier', 'ALDI', '202735 Gewürzq.'),
    ('Pelzy Vlieswindeln', 'Baby und Kind', 'dm', 'Pelzy Vlieswindeln 30S'),
    ('C&A Baby Accessoires', 'Baby und Kind', 'C&A', 'B-ACCESS. Farbe 1 Große 047'),
    ('C&A Baby Accessoires', 'Baby und Kind', 'C&A', 'B-ACCESS. Größe 047'),
    ('C&A Baby Accessoires', 'Baby und Kind', 'C&A', 'B-ACCESS. Größe 070'),
    ('C&A Baby Tops', 'Baby und Kind', 'C&A', 'J BB TOPS Größe 074'),
    ('C&A Baby Hose', 'Baby und Kind', 'C&A', 'J BB TROUSERS Farbe 1 Große 068'),
    ('C&A Baby Tageswaesche', 'Baby und Kind', 'C&A', 'KI-TAGESW Größe 068'),
    ('Bratkasseler', 'Fleisch und Wurst', 'EDEKA', 'BRATKASSELER'),
    ('Paprikalyoner', 'Fleisch und Wurst', 'EDEKA', 'E.Regio.Papr.Lyon.'),
    ('Schinkenwurst', 'Fleisch und Wurst', 'EDEKA', 'E.Regio.Sch.Wurst'),
    ('Erdbeeren', 'Salat, Obst & Gemüse', 'EDEKA', 'Erdbeeren'),
    ('Gut und Guenstig Butter', 'Milchprodukte und Eier', 'EDEKA', 'G&G B.O.Butte'),
    ('Gut und Guenstig Honigjoghurt', 'Milchprodukte und Eier', 'EDEKA', 'G&G Joghurt Hon.'),
    ('Gut und Guenstig Petersilie', 'Salat, Obst & Gemüse', 'EDEKA', 'G&G Petersilie'),
    ('Gefluegelmortadella', 'Fleisch und Wurst', 'EDEKA', 'GEFLUEGELMORT'),
    ('Hinterschinken', 'Fleisch und Wurst', 'EDEKA', 'HINTERSCHINK'),
    ('Landliebe Erdbeer-Konfituere', 'Vorrat und Fertiggerichte', 'EDEKA', 'Landl.Erdb.Konfi.'),
    ('Merci Petits Kaffee', 'Suesswaren und Snacks', 'EDEKA', 'Merci Petits Kaff.'),
    ('Schinkenwurst', 'Fleisch und Wurst', 'EDEKA', 'Schinkenwurst'),
    ('Zimmermann Farmschinken', 'Fleisch und Wurst', 'EDEKA', 'Zimm.Farm.Schinken'),
    ('Windrad', 'Baumarkt und Garten', 'Jawoll', 'Windrad bunt mit Bia'),
    ('Gebaeckschritte', 'Suesswaren und Snacks', 'Jawoll', 'Gebäckschritten');

insert into product_family (name, default_category_id)
select distinct mapping.family_name, category.id
from additional_product_seed_mapping mapping
join category on category.name = mapping.category_name
on conflict (name) do nothing;

insert into product_rule (
    product_family_id,
    store_name,
    match_type,
    match_value,
    priority
)
select distinct
    family.id,
    mapping.store_name,
    'EXACT',
    mapping.match_value,
    100
from additional_product_seed_mapping mapping
join product_family family on family.name = mapping.family_name
where not exists (
    select 1
    from product_rule existing
    where existing.product_family_id = family.id
      and existing.product_variant_id is null
      and existing.store_name is not distinct from mapping.store_name
      and existing.match_type = 'EXACT'
      and existing.match_value = mapping.match_value
);
