INSERT INTO category (name, color_hex, icon, sort_order) VALUES
    ('Obst und Gemuese', '#43A047', 'apple', 11),
    ('Fleisch und Wurst', '#B71C1C', 'beef', 12),
    ('Milchprodukte und Eier', '#00838F', 'milk', 13),
    ('Brot und Backwaren', '#8D6E63', 'wheat', 14),
    ('Suesswaren und Snacks', '#AD1457', 'cookie', 15),
    ('Vorrat und Fertiggerichte', '#5D4037', 'package', 16),
    ('Koerperpflege', '#7B1FA2', 'sparkles', 31),
    ('Baby und Kind', '#D81B60', 'baby', 32),
    ('Pfand und Rabatte', '#546E7A', 'receipt', 90),
    ('Baumarkt und Garten', '#558B2F', 'hammer', 100),
    ('Mobilitaet und Tanken', '#F57F17', 'fuel', 110),
    ('Gastronomie', '#6D4C41', 'utensils', 120)
ON CONFLICT (name) DO NOTHING;

WITH seed_rules(category_name, match_field, match_type, match_value, priority) AS (
    VALUES
        ('Pfand und Rabatte', 'DESCRIPTION', 'CONTAINS', 'PFAND', 5),
        ('Pfand und Rabatte', 'DESCRIPTION', 'CONTAINS', 'RABATT', 5),
        ('Pfand und Rabatte', 'DESCRIPTION', 'CONTAINS', 'COUPON', 5),
        ('Pfand und Rabatte', 'DESCRIPTION', 'CONTAINS', 'GRATIS', 5),
        ('Pfand und Rabatte', 'DESCRIPTION', 'CONTAINS', 'VORTEIL', 5),

        ('Fleisch und Wurst', 'DESCRIPTION', 'CONTAINS', 'SCHINKEN', 20),
        ('Fleisch und Wurst', 'DESCRIPTION', 'CONTAINS', 'WURST', 20),
        ('Fleisch und Wurst', 'DESCRIPTION', 'CONTAINS', 'SALAMI', 20),
        ('Fleisch und Wurst', 'DESCRIPTION', 'CONTAINS', 'BRATEN', 20),
        ('Fleisch und Wurst', 'DESCRIPTION', 'CONTAINS', 'HACKFLEISCH', 20),
        ('Fleisch und Wurst', 'DESCRIPTION', 'CONTAINS', 'FILET', 20),
        ('Fleisch und Wurst', 'DESCRIPTION', 'CONTAINS', 'FLEISCH', 20),
        ('Fleisch und Wurst', 'DESCRIPTION', 'CONTAINS', 'METT', 20),
        ('Fleisch und Wurst', 'DESCRIPTION', 'CONTAINS', 'KASSLER', 20),
        ('Fleisch und Wurst', 'DESCRIPTION', 'CONTAINS', 'KASSELER', 20),
        ('Fleisch und Wurst', 'DESCRIPTION', 'CONTAINS', 'LYONER', 20),
        ('Fleisch und Wurst', 'DESCRIPTION', 'CONTAINS', 'MORTAD', 20),
        ('Fleisch und Wurst', 'DESCRIPTION', 'CONTAINS', 'LEBERW', 20),
        ('Fleisch und Wurst', 'DESCRIPTION', 'CONTAINS', 'STEAK', 20),
        ('Fleisch und Wurst', 'DESCRIPTION', 'CONTAINS', 'GULASCH', 20),
        ('Fleisch und Wurst', 'DESCRIPTION', 'CONTAINS', 'GEFLUEGEL', 20),

        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'BANANE', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'APFEL', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'KAROTTE', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'TOMATE', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'CHAMPIGNON', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'PAPRIKA', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'ZUCCHINI', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'ZWIEBEL', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'KARTOFFEL', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'GURKE', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'BLUMENKOHL', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'KIWI', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'MANDARINE', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'ANANAS', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'BIRNE', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'ERDBEERE', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'PORREE', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'LAUCH', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'SALAT', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'SPINAT', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'ERBSEN', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'BOHNEN', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'MAIS', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'SPARGEL', 30),
        ('Obst und Gemuese', 'DESCRIPTION', 'CONTAINS', 'OBST/GEMUESE', 30),

        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'KINDER', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'SMARTIES', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'HARIBO', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'SCHOKO', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'CHOCO', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'MILKY', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'DUPLO', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'HANUTA', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'CORNY', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'BONBON', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'MERCI', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'MOZART', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'COOKIE', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'PICK UP', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'CELEBRATIONS', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'KIT KAT', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'LION', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'AMICELLI', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'CHIPS', 35),
        ('Suesswaren und Snacks', 'DESCRIPTION', 'CONTAINS', 'ERDNUESSE', 35),

        ('Milchprodukte und Eier', 'DESCRIPTION', 'CONTAINS', 'H-MILCH', 45),
        ('Milchprodukte und Eier', 'DESCRIPTION', 'CONTAINS', 'MILCH', 45),
        ('Milchprodukte und Eier', 'DESCRIPTION', 'CONTAINS', 'SCHLAGSAHNE', 45),
        ('Milchprodukte und Eier', 'DESCRIPTION', 'CONTAINS', 'SCHMAND', 45),
        ('Milchprodukte und Eier', 'DESCRIPTION', 'CONTAINS', 'JOGHURT', 45),
        ('Milchprodukte und Eier', 'DESCRIPTION', 'CONTAINS', 'PUDDING', 45),
        ('Milchprodukte und Eier', 'DESCRIPTION', 'CONTAINS', 'KAESE', 45),
        ('Milchprodukte und Eier', 'DESCRIPTION', 'CONTAINS', 'MOZZA', 45),
        ('Milchprodukte und Eier', 'DESCRIPTION', 'CONTAINS', 'BRESSO', 45),
        ('Milchprodukte und Eier', 'DESCRIPTION', 'CONTAINS', 'BUTTER', 45),
        ('Milchprodukte und Eier', 'DESCRIPTION', 'CONTAINS', 'QUARK', 45),
        ('Milchprodukte und Eier', 'DESCRIPTION', 'CONTAINS', 'MONTE', 45),
        ('Milchprodukte und Eier', 'DESCRIPTION', 'CONTAINS', 'ACTIMEL', 45),
        ('Milchprodukte und Eier', 'DESCRIPTION', 'CONTAINS', 'EIER', 45),

        ('Brot und Backwaren', 'DESCRIPTION', 'CONTAINS', 'TOAST', 50),
        ('Brot und Backwaren', 'DESCRIPTION', 'CONTAINS', 'BAGUETTE', 50),
        ('Brot und Backwaren', 'DESCRIPTION', 'CONTAINS', 'BROT', 50),
        ('Brot und Backwaren', 'DESCRIPTION', 'CONTAINS', 'BROETCHEN', 50),
        ('Brot und Backwaren', 'DESCRIPTION', 'CONTAINS', 'WEIZENVOLLK', 50),
        ('Brot und Backwaren', 'DESCRIPTION', 'CONTAINS', 'TORTILLAS', 50),

        ('Getraenke', 'DESCRIPTION', 'CONTAINS', 'COCA', 55),
        ('Getraenke', 'DESCRIPTION', 'CONTAINS', 'COLA', 55),
        ('Getraenke', 'DESCRIPTION', 'CONTAINS', 'SPRITE', 55),
        ('Getraenke', 'DESCRIPTION', 'CONTAINS', 'SAFT', 55),
        ('Getraenke', 'DESCRIPTION', 'CONTAINS', 'WASSER', 55),
        ('Getraenke', 'DESCRIPTION', 'CONTAINS', 'QUELLE', 55),
        ('Getraenke', 'DESCRIPTION', 'CONTAINS', 'MULTIVITAMIN', 55),
        ('Getraenke', 'DESCRIPTION', 'CONTAINS', 'BELLA CREMA', 55),
        ('Getraenke', 'DESCRIPTION', 'CONTAINS', 'ROTB.', 55),
        ('Getraenke', 'DESCRIPTION', 'CONTAINS', 'LA CREMA', 55),

        ('Vorrat und Fertiggerichte', 'DESCRIPTION', 'CONTAINS', 'SAUCE', 65),
        ('Vorrat und Fertiggerichte', 'DESCRIPTION', 'CONTAINS', 'HOLLANDAISE', 65),
        ('Vorrat und Fertiggerichte', 'DESCRIPTION', 'CONTAINS', 'SAUCENBINDER', 65),
        ('Vorrat und Fertiggerichte', 'DESCRIPTION', 'CONTAINS', 'TOMATEN STUECKIG', 65),
        ('Vorrat und Fertiggerichte', 'DESCRIPTION', 'CONTAINS', 'PASTE', 65),
        ('Vorrat und Fertiggerichte', 'DESCRIPTION', 'CONTAINS', 'BASMATI', 65),
        ('Vorrat und Fertiggerichte', 'DESCRIPTION', 'CONTAINS', 'REIS', 65),
        ('Vorrat und Fertiggerichte', 'DESCRIPTION', 'CONTAINS', 'KIDNEY', 65),
        ('Vorrat und Fertiggerichte', 'DESCRIPTION', 'CONTAINS', 'MEHL', 65),
        ('Vorrat und Fertiggerichte', 'DESCRIPTION', 'CONTAINS', 'GEWUERZ', 65),
        ('Vorrat und Fertiggerichte', 'DESCRIPTION', 'CONTAINS', 'SPAGH', 65),
        ('Vorrat und Fertiggerichte', 'DESCRIPTION', 'CONTAINS', 'BOLOGN', 65),
        ('Vorrat und Fertiggerichte', 'DESCRIPTION', 'CONTAINS', 'DRESSING', 65),
        ('Vorrat und Fertiggerichte', 'DESCRIPTION', 'CONTAINS', 'ROTKOHL', 65),
        ('Vorrat und Fertiggerichte', 'DESCRIPTION', 'CONTAINS', 'BRATKARTOFFELN', 65),
        ('Vorrat und Fertiggerichte', 'DESCRIPTION', 'CONTAINS', 'FISCHSTAEBCHEN', 65),

        ('Koerperpflege', 'DESCRIPTION', 'CONTAINS', 'BALEA', 70),
        ('Koerperpflege', 'DESCRIPTION', 'CONTAINS', 'NIVEA', 70),
        ('Koerperpflege', 'DESCRIPTION', 'CONTAINS', 'DOVE', 70),
        ('Koerperpflege', 'DESCRIPTION', 'CONTAINS', 'REXONA', 70),
        ('Koerperpflege', 'DESCRIPTION', 'CONTAINS', 'DEO', 70),
        ('Koerperpflege', 'DESCRIPTION', 'CONTAINS', 'ODOL', 70),
        ('Koerperpflege', 'DESCRIPTION', 'CONTAINS', 'DR. BEST', 70),
        ('Koerperpflege', 'DESCRIPTION', 'CONTAINS', 'ZAHN', 70),
        ('Koerperpflege', 'DESCRIPTION', 'CONTAINS', 'DUSCHE', 70),
        ('Koerperpflege', 'DESCRIPTION', 'CONTAINS', 'SHAMPOO', 70),
        ('Koerperpflege', 'DESCRIPTION', 'CONTAINS', 'TROCKSH', 70),
        ('Koerperpflege', 'DESCRIPTION', 'CONTAINS', 'TROCKENSH', 70),
        ('Koerperpflege', 'DESCRIPTION', 'CONTAINS', 'TUCHMASKE', 70),
        ('Koerperpflege', 'DESCRIPTION', 'CONTAINS', 'AUGENPAD', 70),
        ('Koerperpflege', 'DESCRIPTION', 'CONTAINS', 'HORNHAUT', 70),
        ('Koerperpflege', 'DESCRIPTION', 'CONTAINS', 'FUSSBUTTER', 70),
        ('Koerperpflege', 'DESCRIPTION', 'CONTAINS', 'PFLEGEOEL', 70),
        ('Koerperpflege', 'DESCRIPTION', 'CONTAINS', 'PFLEGEÖL', 70),

        ('Baby und Kind', 'DESCRIPTION', 'CONTAINS', 'BABYLOVE', 75),
        ('Baby und Kind', 'DESCRIPTION', 'CONTAINS', 'WICKEL', 75),
        ('Baby und Kind', 'DESCRIPTION', 'CONTAINS', 'BETTEINLAGEN', 75),
        ('Baby und Kind', 'DESCRIPTION', 'CONTAINS', 'BELLA MAMMA', 75),
        ('Baby und Kind', 'DESCRIPTION', 'CONTAINS', 'SCHWANGERSCH', 75),
        ('Baby und Kind', 'DESCRIPTION', 'CONTAINS', 'MAMMA', 75),

        ('Gesundheit', 'DESCRIPTION', 'CONTAINS', 'RICOLA', 80),
        ('Gesundheit', 'DESCRIPTION', 'CONTAINS', 'TENA', 80),
        ('Gesundheit', 'DESCRIPTION', 'CONTAINS', 'ALWAYS', 80),
        ('Gesundheit', 'DESCRIPTION', 'CONTAINS', 'PFLASTER', 80),
        ('Gesundheit', 'DESCRIPTION', 'CONTAINS', 'VERBAND', 80),
        ('Gesundheit', 'DESCRIPTION', 'CONTAINS', 'NASENSPRAY', 80),
        ('Gesundheit', 'DESCRIPTION', 'CONTAINS', 'IBUPROFEN', 80),
        ('Gesundheit', 'DESCRIPTION', 'CONTAINS', 'PARACETAMOL', 80),
        ('Gesundheit', 'DESCRIPTION', 'CONTAINS', 'MAGNESIUM', 80),
        ('Gesundheit', 'STORE_NAME', 'CONTAINS', 'APOTHEKE', 80),
        ('Gesundheit', 'STORE_NAME', 'CONTAINS', 'DOCMORRIS', 80),

        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'TOILETTENPAP', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'TOIPA', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'KUECHENTUECHER', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'TATUE', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'TATÜ', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'TUECHER', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'TÜCHER', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'SCHWAMM', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'STAUBTUECHER', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'KLARSICHT', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'ALUMINIUMFOLIE', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'REINIGER', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'GALLSEIFE', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'DENKMIT', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'PROF.', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'COLOR KRAFT GEL', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'DUFT-GEL', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'LUFTERFR', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'DESINFEKTION', 90),
        ('Haushalt', 'DESCRIPTION', 'CONTAINS', 'EINKAUFSTASCHE', 90),

        ('Freizeit', 'DESCRIPTION', 'CONTAINS', 'GIFT CARD', 100),
        ('Freizeit', 'DESCRIPTION', 'CONTAINS', 'GESCHENK', 100),
        ('Freizeit', 'DESCRIPTION', 'CONTAINS', 'GRUSSKARTE', 100),
        ('Freizeit', 'DESCRIPTION', 'CONTAINS', 'GRUSZKARTE', 100),
        ('Freizeit', 'DESCRIPTION', 'CONTAINS', 'ADVENTSKALENDER', 100),

        ('Baumarkt und Garten', 'STORE_NAME', 'CONTAINS', 'OBI', 110),
        ('Baumarkt und Garten', 'STORE_NAME', 'CONTAINS', 'BAUHAUS', 110),
        ('Baumarkt und Garten', 'STORE_NAME', 'CONTAINS', 'HORNBACH', 110),
        ('Baumarkt und Garten', 'STORE_NAME', 'CONTAINS', 'TOOM', 110),
        ('Baumarkt und Garten', 'STORE_NAME', 'CONTAINS', 'HAGEBAU', 110),
        ('Baumarkt und Garten', 'STORE_NAME', 'CONTAINS', 'GLOBUS BAUMARKT', 110),
        ('Baumarkt und Garten', 'DESCRIPTION', 'CONTAINS', 'WERKZEUG', 110),
        ('Baumarkt und Garten', 'DESCRIPTION', 'CONTAINS', 'SCHRAUBE', 110),
        ('Baumarkt und Garten', 'DESCRIPTION', 'CONTAINS', 'DUEBEL', 110),
        ('Baumarkt und Garten', 'DESCRIPTION', 'CONTAINS', 'FARBE', 110),
        ('Baumarkt und Garten', 'DESCRIPTION', 'CONTAINS', 'LACK', 110),
        ('Baumarkt und Garten', 'DESCRIPTION', 'CONTAINS', 'PINSEL', 110),
        ('Baumarkt und Garten', 'DESCRIPTION', 'CONTAINS', 'BLUMENERDE', 110),
        ('Baumarkt und Garten', 'DESCRIPTION', 'CONTAINS', 'GARTEN', 110),

        ('Mobilitaet und Tanken', 'STORE_NAME', 'CONTAINS', 'ARAL', 120),
        ('Mobilitaet und Tanken', 'STORE_NAME', 'CONTAINS', 'SHELL', 120),
        ('Mobilitaet und Tanken', 'STORE_NAME', 'CONTAINS', 'ESSO', 120),
        ('Mobilitaet und Tanken', 'STORE_NAME', 'CONTAINS', 'JET', 120),
        ('Mobilitaet und Tanken', 'STORE_NAME', 'CONTAINS', 'AVIA', 120),
        ('Mobilitaet und Tanken', 'STORE_NAME', 'CONTAINS', 'TOTAL', 120),
        ('Mobilitaet und Tanken', 'STORE_NAME', 'CONTAINS', 'TANK', 120),
        ('Mobilitaet und Tanken', 'DESCRIPTION', 'CONTAINS', 'DIESEL', 120),
        ('Mobilitaet und Tanken', 'DESCRIPTION', 'CONTAINS', 'SUPER E10', 120),
        ('Mobilitaet und Tanken', 'DESCRIPTION', 'CONTAINS', 'BENZIN', 120),
        ('Mobilitaet und Tanken', 'DESCRIPTION', 'CONTAINS', 'KRAFTSTOFF', 120),
        ('Mobilitaet und Tanken', 'DESCRIPTION', 'CONTAINS', 'ADBLUE', 120),

        ('Gastronomie', 'STORE_NAME', 'CONTAINS', 'RESTAURANT', 130),
        ('Gastronomie', 'STORE_NAME', 'CONTAINS', 'IMBISS', 130),
        ('Gastronomie', 'STORE_NAME', 'CONTAINS', 'CAFE', 130),
        ('Gastronomie', 'STORE_NAME', 'CONTAINS', 'BISTRO', 130),
        ('Gastronomie', 'STORE_NAME', 'CONTAINS', 'MCDONALD', 130),
        ('Gastronomie', 'STORE_NAME', 'CONTAINS', 'BURGER KING', 130),
        ('Gastronomie', 'STORE_NAME', 'CONTAINS', 'KFC', 130),
        ('Gastronomie', 'STORE_NAME', 'CONTAINS', 'SUBWAY', 130),
        ('Gastronomie', 'STORE_NAME', 'CONTAINS', 'LIEFERANDO', 130),

        ('Tierbedarf', 'DESCRIPTION', 'CONTAINS', 'HUNDE', 150),
        ('Tierbedarf', 'DESCRIPTION', 'CONTAINS', 'KATZEN', 150),
        ('Tierbedarf', 'DESCRIPTION', 'CONTAINS', 'TIERFUTTER', 150),
        ('Tierbedarf', 'DESCRIPTION', 'CONTAINS', 'FUTTER', 150),

        ('Lebensmittel', 'STORE_NAME', 'CONTAINS', 'REWE', 900),
        ('Lebensmittel', 'STORE_NAME', 'CONTAINS', 'ALDI', 900),
        ('Lebensmittel', 'STORE_NAME', 'CONTAINS', 'LIDL', 900),
        ('Lebensmittel', 'STORE_NAME', 'CONTAINS', 'EDEKA', 900),
        ('Lebensmittel', 'STORE_NAME', 'CONTAINS', 'KAUFLAND', 900),
        ('Lebensmittel', 'STORE_NAME', 'CONTAINS', 'NETTO', 900),
        ('Lebensmittel', 'STORE_NAME', 'CONTAINS', 'PENNY', 900),
        ('Drogerie', 'STORE_NAME', 'CONTAINS', 'DM', 900),
        ('Drogerie', 'STORE_NAME', 'CONTAINS', 'ROSSMANN', 900),
        ('Drogerie', 'STORE_NAME', 'CONTAINS', 'MUELLER', 900)
)
INSERT INTO categorization_rule (category_id, match_field, match_type, match_value, priority)
SELECT category.id, seed_rules.match_field, seed_rules.match_type, seed_rules.match_value, seed_rules.priority
FROM seed_rules
JOIN category ON category.name = seed_rules.category_name
WHERE NOT EXISTS (
    SELECT 1
    FROM categorization_rule existing_rule
    WHERE existing_rule.category_id = category.id
        AND existing_rule.match_field = seed_rules.match_field
        AND existing_rule.match_type = seed_rules.match_type
        AND existing_rule.match_value = seed_rules.match_value
        AND existing_rule.priority = seed_rules.priority
);
